### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by lencioni** [sds/gerrit#8]
I just tried pushing to gerrit and got this stack trace.

```
Finding matching users/groups...-
Command `ssh -p 29418 my.username@my.gerrit.host gerrit ls-members 'Engineers' --recursive` failed:
STATUS: 128
STDOUT: ""
STDERR: "fatal: internal server error\n"

/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gerrit-0.7.1/lib/gerrit/client.rb:25:in `execute'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gerrit-0.7.1/lib/gerrit/client.rb:51:in `group_members'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gerrit-0.7.1/lib/gerrit/client.rb:94:in `block in users'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gerrit-0.7.1/lib/gerrit/utils.rb:53:in `call'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gerrit-0.7.1/lib/gerrit/utils.rb:53:in `block in map_in_parallel'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:408:in `call'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:408:in `call_with_index'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:288:in `block (2 levels) in work_in_threads'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:419:in `with_instrumentation'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:287:in `block in work_in_threads'
/Users/joe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parallel-1.6.1/lib/parallel.rb:183:in `block (2 levels) in in_threads'
Report this bug at https://github.com/sds/gerrit/issues

To help fix this issue, please include:
- The above stack trace
- Ruby version: 2.2.3
```

Pushing it a second time worked without a problem.

I don't think the problem is in this gem, but perhaps this error could be handled better?

**Comment by sds** [comment]
Good point. I've changed the CLI in 2ff70108048401a31fdb04cd14853a467497342c to treat Gerrit Server-related errors as something outside of the control of the `gerrit` gem, so it won't dump a full stack trace.
